# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-10-01 09:30
from __future__ import unicode_literals

import Main.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_name', models.CharField(max_length=50)),
                ('loan_amount', models.PositiveIntegerField()),
                ('no_of_years', models.IntegerField(default=20)),
                ('date_of_payment', models.DateField(default=django.utils.timezone.now)),
                ('rate_of_interest', models.FloatField(default=10.0)),
                ('type', models.CharField(max_length=15)),
                ('is_calender', models.BooleanField(default=False)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            bases=(models.Model, Main.models.Main),
        ),
        migrations.CreateModel(
            name='Premium',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lic_name', models.CharField(max_length=50, null=True)),
                ('start_date', models.DateField(null=True)),
                ('end_date', models.DateField()),
                ('type', models.CharField(max_length=15)),
                ('premium_amount', models.PositiveIntegerField()),
                ('end_year', models.DateField()),
                ('is_calender', models.BooleanField(default=False)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            bases=(models.Model, Main.models.Main),
        ),
    ]
