# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-10-01 09:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0002_loan_premium'),
    ]

    operations = [
        migrations.AlterField(
            model_name='premium',
            name='end_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='premium',
            name='end_year',
            field=models.DateField(null=True),
        ),
    ]
