# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-10-01 09:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0003_auto_20161001_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='premium',
            name='type',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
