# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-10-01 09:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0004_auto_20161001_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='premium',
            name='premium_amount',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
