# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-10-01 15:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0005_auto_20161001_1526'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='flag',
            field=models.IntegerField(default=0),
        ),
    ]
