# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-10-03 07:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0006_userdetails_flag'),
    ]

    operations = [
        migrations.AddField(
            model_name='balance',
            name='total',
            field=models.FloatField(default=0),
        ),
    ]
