# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-10-03 17:09
from __future__ import unicode_literals

import Main.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Main', '0010_auto_20161003_1436'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanPremium',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_premium_name', models.CharField(max_length=50, null=True)),
                ('loan_premium_amount', models.PositiveIntegerField(null=True)),
                ('start_date', models.DateField(null=True)),
                ('end_date', models.DateField(default=2004, null=True)),
                ('description', models.CharField(max_length=200, null=True)),
                ('no_of_years', models.IntegerField(default=20, null=True)),
                ('rate_of_interest', models.FloatField(default=10.0, null=True)),
                ('type_loan_premium', models.CharField(max_length=15, null=True)),
                ('type_duration', models.CharField(max_length=15, null=True)),
                ('is_calender', models.BooleanField(default=False)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            bases=(models.Model, Main.models.Main),
        ),
        migrations.RemoveField(
            model_name='loan',
            name='user',
        ),
        migrations.RemoveField(
            model_name='premium',
            name='user',
        ),
        migrations.DeleteModel(
            name='Loan',
        ),
        migrations.DeleteModel(
            name='Premium',
        ),
    ]
