# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-10-03 20:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0011_auto_20161003_2239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='profile'),
        ),
    ]
