# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-10-04 04:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0012_auto_20161004_0132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='photo',
            field=models.ImageField(default='\\static\\Main\\images\noimage.png', upload_to='profile'),
        ),
    ]
