# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-10-04 05:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0014_balance_tax'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='balance',
            name='tax',
        ),
    ]
